---
title: "Outreach"
---

**Sonophilia Foundation**

[Sonophilia Foundation Website](https://www.sonophilia.com/hannah-merseal/)

This is an article and podcast episode about my research and work with Sonophilia. Look out for more about our Creativity Factbook project later this year.

**ootiboo**

[ootiboo website](https://www.ootiboo.com/)

I am working with ootiboo, a new arts intervention program, to conduct a longitudinal study on creativity development in middle childhood. Stay tuned for more on this project soon.

**How Can We Measure Creativity?**

[Link](https://sites.psu.edu/linguisticexperiments/measuring-creativity/)

This is an outreach activity I wrote as an affiliate of the [Penn State Center for Language Science](https://cls.la.psu.edu/). It is a short explanation of the scientific study of creativity and an adapted Alternate Uses Task targeted towards a late-elementary to early-middle school audience. 

**Bilingualism Matters At PSU: Summer/Fall 2021**

[Link](https://sites.psu.edu/bilingualismmatters/)

I collaborated on this issue as an affiliate of the Center for Language Science. This issue revolves around the theme of online language learning, particularly in the context of the COVID-19 pandemic. I contributed [this research article](https://sites.psu.edu/bilingualismmatters/virtual-language-learning-in-2020-challenges-and-innovations/), "Virtual Language Learning in 2020: Challenges and Innovations".
