---
title: "Presentations"
---

**The Melodicon: Representing Melodic Relationships Using Network Science**

[Video](https://www.youtube.com/watch?v=6Ooy-KcNeXw)

Presentation given at [ICMPC16/ESCOM11](https://sites.google.com/sheffield.ac.uk/escom2021/home), July 2021.

**Melodic Choice Tasks in psychTestR**

Created for PSY 525, Reproducibile Research Methods, Spring 2020. This is a demo of a melodic choice task using psychTestR to present participants with pairs of melodies. 

[Document](https://hannah-merseal.shinyapps.io/psychTestR-525-document/)

[Slides](https://hannah-merseal.shinyapps.io/psychTestR-525-slides/)

[Task Repository](https://github.com/hannah-merseal/jazz-choice-task)

**Sequencing Biases in Musical Improvisation: Evidence from Large Scale Corpus Analysis**

A talk given at the PSU Cognitive Area Brownbag in October 2020. This is an overview of our Easy First paper that highlights some ongoing related projects.

[Slides](https://drive.google.com/file/d/1Sw_j8PLizmqFYOnMcY7fEYcNJjI7KkzH/view?usp=sharing)

**Sequencing Biases in Musical Improvisation: SfNC Data Blitz**

A data blitz talk given at the [2020 SfNC meeting](https://www.tsfnc.org/). This is the 5-minute version of the previous presentation.

[Video](https://www.crowdcast.io/e/5j3xpaqy/4)
[Slides](https://osf.io/2n9bk/)

**Sequencing Biases in Musical Improvisation: FDoMC poster talk**

A 5-minute poster presentation given at the 2021 [Future Directions of Music Cognition](http://org.osu.edu/mascats/) virtual conference. 

[Slides and Video](https://osf.io/b7kfv/)

